services:
  - type: web
    name: codecollob
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
